### ISSUE TITLE
No such module 'Smile_Identity_SDK'

### ISSUE THREAD

**Issue by shashankbhavsar1992** [smileidentity/react-native-sample-app#7]
Hi,
I am getting error as No such module 'Smile_Identity_SDK' after installing    "rn-smile-id": "^0.0.50",  in ios  issue is coming in import Smile_Identity_SDK

@objc(RnSmileId)
class RnSmileId: NSObject ,SIDCaptureManagerDelegate ,SIDNetworkRequestDelegate, SIDConsentManagerDelegate, BVNConsentResultDelegate {}

**Comment by beastawakens** [comment]
@shashankbhavsar1992 Apologies, this repo is no longer maintained. Up to date instructions can be found here: https://github.com/smileidentity/react-native
